### ISSUE TITLE
Other APIs

### ISSUE THREAD

**Issue by motowntalent** [yannikkellerde/AI-Snip#4]
Is it possible to add other APIs like Groq or Gemini? Is that on the roadmap?

**Comment by yannikkellerde** [comment]
If you know a little bit of python and know how the api you want to use works, then it should be very easy to add another model_wrapper and create a pull request which I'll happily merge. Check [openai_model_wrapper.py](https://github.com/yannikkellerde/AI-Snip/blob/main/openai_model_wrapper.py) to get started.

From my side, there is no roadmap or anything. I'll only update this project myself with changes that make it more convenient for my day to day use.
